//
//  JzStyleKit.h
//  JETZUN™
//
//  Created by Charles P Ajemian on 12/2/15.
//  Copyright (c) 2015 JETZUN™. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>



@interface JzStyleKit : NSObject

// Colors
+ (UIColor*)jzGrey;

// Shadows
+ (NSShadow*)jzDropShadow;

// Generated Images
+ (UIImage*)imageOfJzCardWithJzCardFrame: (CGRect)jzCardFrame rectangle2: (CGRect)rectangle2;

@end



@interface NSShadow (PaintCodeAdditions)

+ (instancetype)shadowWithColor: (UIColor*)color offset: (CGSize)offset blurRadius: (CGFloat)blurRadius;
- (void)set;

@end
