//
//  PharmaStyle.h
//  NCLEX-RN
//
//  Created by CAjemian on 12/12/15.
//  Copyright (c) 2015 HOBAJEM. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@class PCGradient;

@interface PharmaStyle : NSObject

// Colors
+ (UIColor*)colorAppWhite;
+ (UIColor*)colorAppBlack;
+ (UIColor*)colorBlueHighlight;
+ (UIColor*)colorBlue;
+ (UIColor*)colorRedHighlight;
+ (UIColor*)colorRed;
+ (UIColor*)colorYellow;
+ (UIColor*)colorYellowDark;
+ (UIColor*)colorOrange;
+ (UIColor*)colorGreenHightlight;
+ (UIColor*)colorRedLight;
+ (UIColor*)colorRedShadow50;
+ (UIColor*)colorRedBright;
+ (UIColor*)colorBlueLight;
+ (UIColor*)colorBlueShadow;
+ (UIColor*)colorAppBlack50;
+ (UIColor*)colorBlueHighlight0;
+ (UIColor*)colorAppWhite50;
+ (UIColor*)colorAppBlack20;
+ (UIColor*)colorRedShadow70;

// Gradients
+ (PCGradient*)gradOrange;
+ (PCGradient*)gradBlue;
+ (PCGradient*)gradient;

// Shadows
+ (NSShadow*)shadowBlack50;
+ (NSShadow*)shadowBlackDark;
+ (NSShadow*)shadowBlackDark0;

// Drawing Methods
+ (void)drawGfxNurseHatWithIconFrameHat: (CGRect)iconFrameHat;
+ (void)drawButtonPillsWithButtonFrame: (CGRect)buttonFrame varPressed: (BOOL)varPressed;
+ (void)drawButtonMedsWithButtonFrame: (CGRect)buttonFrame;
+ (void)drawButtonHomeWithButtonFrame: (CGRect)buttonFrame varPressed: (BOOL)varPressed;
+ (void)drawButtonPharmaWithButtonFrame: (CGRect)buttonFrame varPressed: (BOOL)varPressed;
+ (void)drawButtonRootWithButtonFrame: (CGRect)buttonFrame varPressed: (BOOL)varPressed;
+ (void)drawButtonStarWithButtonFrame: (CGRect)buttonFrame varPressed: (BOOL)varPressed;
+ (void)drawButtonMenuWithButtonFrame: (CGRect)buttonFrame varPressed: (BOOL)varPressed;
+ (void)drawIconCheckCircleWithButtonFrame: (CGRect)buttonFrame;
+ (void)drawIconCloseCircleWithButtonFrame: (CGRect)buttonFrame;
+ (void)drawButtonArrowWithButtonFrame: (CGRect)buttonFrame varPressed: (BOOL)varPressed;
+ (void)drawButtonCheckMarkWithButtonFrame: (CGRect)buttonFrame varPressed: (BOOL)varPressed;
+ (void)drawButtonMoreWithButtonFrame: (CGRect)buttonFrame varPressed: (BOOL)varPressed;
+ (void)drawBannerLaunchWithBannerFrame: (CGRect)bannerFrame;
+ (void)drawTxtFieldTitleWithTextFieldFrame: (CGRect)textFieldFrame
                          varTextfieldTitle: (NSString*)varTextfieldTitle
                                varFontSize: (CGFloat)varFontSize;
+ (void)drawBannerReferenceWithBannerFrame: (CGRect)bannerFrame;
+ (void)drawTxtFieldHeaderWithTextFieldFrame: (CGRect)textFieldFrame;
+ (void)drawBannerTestingWithBannerFrame: (CGRect)bannerFrame;
+ (void)drawBannerReferenceTermWithBannerFrame: (CGRect)bannerFrame;
+ (void)drawBannerReferenceTermExpandedWithBannerFrameExpanded: (CGRect)bannerFrameExpanded;
+ (void)drawBannerTesting2WithBannerFrame: (CGRect)bannerFrame;

// Generated Images

+ (UIImage*)imageOfGfxNurseHatWithIconFrameHat: (CGRect)iconFrameHat;

+ (UIImage*)imageOfButtonPillsWithButtonFrame: (CGRect)buttonFrame varPressed: (BOOL)varPressed;

+ (UIImage*)imageOfButtonMedsWithButtonFrame: (CGRect)buttonFrame;

+ (UIImage*)imageOfButtonHomeWithButtonFrame: (CGRect)buttonFrame varPressed: (BOOL)varPressed;

+ (UIImage*)imageOfButtonPharmaWithButtonFrame: (CGRect)buttonFrame varPressed: (BOOL)varPressed;

+ (UIImage*)imageOfButtonRootWithButtonFrame: (CGRect)buttonFrame varPressed: (BOOL)varPressed;

+ (UIImage*)imageOfButtonStarWithButtonFrame: (CGRect)buttonFrame varPressed: (BOOL)varPressed;

+ (UIImage*)imageOfButtonMenuWithButtonFrame: (CGRect)buttonFrame varPressed: (BOOL)varPressed;

+ (UIImage*)imageOfIconCheckCircleWithButtonFrame: (CGRect)buttonFrame;

+ (UIImage*)imageOfIconCloseCircleWithButtonFrame: (CGRect)buttonFrame;

+ (UIImage*)imageOfButtonArrowWithButtonFrame: (CGRect)buttonFrame varPressed: (BOOL)varPressed;

+ (UIImage*)imageOfButtonCheckMarkWithButtonFrame: (CGRect)buttonFrame varPressed: (BOOL)varPressed;

+ (UIImage*)imageOfButtonMoreWithButtonFrame: (CGRect)buttonFrame varPressed: (BOOL)varPressed;

@end



@interface PCGradient : NSObject
@property(nonatomic, readonly) CGGradientRef CGGradient;
- (CGGradientRef)CGGradient NS_RETURNS_INNER_POINTER;

+ (instancetype)gradientWithColors: (NSArray*)colors locations: (const CGFloat*)locations;
+ (instancetype)gradientWithStartingColor: (UIColor*)startingColor endingColor: (UIColor*)endingColor;

@end



@interface NSShadow (PaintCodeAdditions)

+ (instancetype)shadowWithColor: (UIColor*)color offset: (CGSize)offset blurRadius: (CGFloat)blurRadius;
- (void)set;

@end
